import type {Metadata} from 'next';
import {AppWrapper} from './AppWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({children}: {children: React.ReactNode}) => {
  return (
    <html>
      <head />

      <AppWrapper>{children}</AppWrapper>
    </html>
  );
};

export default RootLayout;
